# DATA-445: In-Class Assignment 16

## 1. (3 points)

$k$-means algorithm can be used for which of the following?

(a) clustering  
(b) feature engineering  
(c) All of the above  
(d) None of the above

(a)&(b)

## 2. (3 points)

The goal for $k$-means cost function is to ________ squared error function where error function represents distance between data points and cluster centroid.

(a) minimize  
(b) maximize  
(c) it depends  
(d) All of the above  
(e) None of the above

(a)

## 3.

Consider the `customers.csv` datafile. This file contains information related to customers' activity on a company website. Below are the description of the variables.

- `ID`: customer ID
- `Visit_Time`: The number of visits to the company's website in a given month.
- `Average_Expense`: The average amount of money that the customer has spend.
- `Sex`: gender of the customer (0: female, 1: male).
- `Age`: age of the customer.

In **Python**, answer the following:

### (a) (3 points)

Using the `pandas` library, read the csv file and create a data-frame called `customers`.

In [1]:
import pandas as pd

customers = pd.read_csv("customers.csv")
customers.head()

   ID  Visit_Time  Average_Expense  Sex  Age
0   1           3              5.7    0   10
1   2           5             14.5    0   27
2   3          16             33.5    0   32
3   4           5             15.9    0   30
4   5          16             24.9    0   23

### (b) (3 points)

Using the appropriate Python commands, remove the `ID` variable.

In [2]:
customers = customers.drop(columns = ["ID"], axis=1)
customers.head()

   Visit_Time  Average_Expense  Sex  Age
0           3              5.7    0   10
1           5             14.5    0   27
2          16             33.5    0   32
3           5             15.9    0   30
4          16             24.9    0   23

### (c) (5 points)

Using the appropriate standardization formula, put all the variables on the same scale. _Hint:_ Notice that `Sex` is a 0-1 variable.

In [3]:

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
customers[["Visit_Time", "Average_Expense", "Age"]] = scaler.fit_transform(customers[["Visit_Time", "Average_Expense", "Age"]])
customers.head()

   Visit_Time  Average_Expense  Sex       Age
0    0.117647         0.041096    0  0.051282
1    0.235294         0.342466    0  0.487179
2    0.882353         0.993151    0  0.615385
3    0.235294         0.390411    0  0.564103
4    0.882353         0.698630    0  0.384615

### (d) (6 points)

Using the `KMeans` function from the `sklearn.cluster` library, cluster the customers into four clusters. Make sure you use standardized variables as the inputs in the $k$-means algorithm, append the cluster labels to the `customers` data-frame, and use `n_init=20` in the `KMeans` function.

In [4]:
from sklearn.cluster import KMeans

# Defing the KMeans model
kmeans = KMeans(n_clusters=4, n_init=20, random_state=42)
kmeans.fit(customers)

# Append the cluster labels to the customers DataFrame
customers["Cluster"] = kmeans.labels_
customers.head()

   Visit_Time  Average_Expense  Sex       Age  Cluster
0    0.117647         0.041096    0  0.051282        0
1    0.235294         0.342466    0  0.487179        0
2    0.882353         0.993151    0  0.615385        3
3    0.235294         0.390411    0  0.564103        0
4    0.882353         0.698630    0  0.384615        3

### (e) (5 points)

Describe each of the clusters from part (d).

In [5]:
customers = pd.read_csv("customers.csv")
customers = customers.drop(columns=["ID"], axis=1)
customers["Cluster"] = kmeans.labels_
customers.head()

   Visit_Time  Average_Expense  Sex  Age  Cluster
0           3              5.7    0   10        0
1           5             14.5    0   27        0
2          16             33.5    0   32        3
3           5             15.9    0   30        0
4          16             24.9    0   23        3

In [6]:
customers.groupby("Cluster").mean()

         Visit_Time  Average_Expense  Sex      Age
Cluster
0          4.909091        12.709091  0.0  17.0000
1          5.560000        10.928000  1.0  15.4800
2         12.250000        25.362500  1.0  31.1875
3         14.375000        25.587500  0.0  26.6250

The younger people do not spend as much time or money as the older clusters.